version: "3"
services:
  es:
    image: elasticsearch:6.4.1
    ports:
      - "9200:9200"
  server:
    image: server
    ports:
      - "4000:4000"
    volumes:
      - /root/benawad.com/server/images:/usr/app/images
    depends_on:
      - es
  web:
    image: web
    ports:
      - "3000:3000"
  proxy:
    image: abiosoft/caddy:no-stats
    volumes:
      - /root/benawad.com/Caddyfile:/etc/Caddyfile
      - /root/.caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - server
